services:
  cards:
    image: "sivakumar1728/cards:v1"
    container_name: cards-ms
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankMicroservice
networks:
  bankMicroservice:
    driver: "bridge"