services:
  network-deploy-services:
    networks:
      - bankMicroservice
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 70m
    environment:
      SPRING_PROFILES_ACTIVE: default
  microservice-configserver-config:
    extends: microservice-base-config