services:
  accountsdb:
    image: postgres
    container_name: accountsdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accountsuser -d accountsdb"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      POSTGRES_USER: accountsuser
      POSTGRES_PASSWORD: password
  configserver:
    image: "sivakumar1728/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness|grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankMicroservice
  cards:
    image: "sivakumar1728/cards:v2"
    container_name: cards-ms
    ports:
      - "8091:8091"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankMicroservice
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:80871/"
      SPRING_PROFILES_ACTIVE: default
networks:
  bankMicroservice:
    driver: "bridge"